### ISSUE TITLE
Missing transform functions (rotateX, rotateY, perspective)

### ISSUE THREAD

**Issue by jeremiahmmv2** [jeremyckahn/rekapi#37]
I'm planning to recreate animate.css animations with Rekapi and noticed that the rotateX, rotateY and perspective functions are missing from the transformFunctions array. 

I was attempting to recreate the flipInX animation when I noticed it.

```css
@keyframes flipInX {
    0% {
        transform: perspective(400px) rotateX(90deg);
        opacity: 0;
    }

    40% {
        transform: perspective(400px) rotateX(-10deg);
    }

    70% {
        transform: perspective(400px) rotateX(10deg);
    }

    100% {
        transform: perspective(400px) rotateX(0deg);
        opacity: 1;
    };
}
```

I added them to transformFunctions in my local version and it seems to work fine in Chrome. Is there a reason they're not available by default?
